config/routes.rb
Rails.application.routes.draw do
  root to: "companies#index"
  resources :policies
  resources :companies do
    post "upload-sheet", on: :collection
  end
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  require 'csv'
  has_many :employees
  has_many :policies
  validates :name, presence: true


  def read_sheet(url)
    puts "------"
    puts "#{url}"
    parent_child = Hash.new
    CSV.foreach(url, headers: true) do |row|
      employee = self.employees.where(email: row["Email"]).first_or_create!(name: row["Employee Name"], phone: row["Phone"])
      parent_child[employee] = row["Report To"]
      policies = row["Assigned Policies"].split("|")
      policies_ids = []
      policies.each do |p|
        policy = self.policies.where(name: p).first_or_create!
        policies_ids.push policy
      end
      employee.policies.destroy_all
      employee.policies<<policies_ids
    end
    msg = []
    parent_child.each do |key, value|
      if value.present?
        parent = Employee.find_by_email(value)
        parent.present? ? key.update!(parent_id: parent.id) : msg.push("Employee with email '#{value}' not exisits.")
      end
    end
    msg
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload_sheet
    unless params[:id].present?
      @company_error = 1
      respond_to do |format|
        format.js 
        return
     end
    end
    unless params[:file].content_type == "text/csv"
      @ext_error = 1
      respond_to do |format|
        format.js 
        return
     end
    end

    @company = Company.find(params[:id])
    response = @company.read_sheet(params[:file].path)
    respond_to do |format|
      if response.length > 0
        format.html { redirect_to companies_url, error: response }
      else
        format.html { redirect_to companies_url, notice: 'File Successfully Uploaded.' }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table class="table table-inverse table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= link_to 'Show', company , class: "btn-primary btn text-white"%></td>
        <td><%= link_to 'Edit', edit_company_path(company), class: "btn-primary btn text-white" %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-warning btn text-white" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path, class: "btn-primary btn text-white" %>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Upload Data
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_tag( upload_sheet_companies_path, method: :post , remote: true, multipart: true) do |f| %>
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Select File</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
           <%= file_field_tag "file" %>
           <%= select_tag :id, options_for_select(@companies.map{|c| [c.name, c.id]}), include_blank: "Select Company" %>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= submit_tag "Upload File", class: "btn btn-primary"%>
        </div>
      </div>
    <% end %>>
    
  </div>
</div>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/companies/upload_sheet.js.erb
<%if @company_error.present? %>
  alert("Please Selct Company");
<%elsif @ext_error.present? %>
  alert("Please selct only .csv file");
<%else%>
  $('#exampleModal').modal('toggle');
<%end%>